from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import collect_outfits

from .workspace import rows_to_entries


def attach_classification(entry: dict[str, Any], prediction: dict[str, Any] | None) -> dict[str, Any]:
    if not prediction:
        return entry
    entry = dict(entry)
    styles = json.loads(_value(prediction, "styles_json") or "[]")
    flags = json.loads(_value(prediction, "flags_json") or "{}")
    manual_presentation = _value(prediction, "manual_presentation")
    manual_styles = json.loads(_value(prediction, "manual_styles_json") or "[]")
    manual_flags = json.loads(_value(prediction, "manual_flags_json") or "{}")
    if manual_styles:
        predicted_scores = {item.get("label"): item.get("confidence", 0) for item in styles}
        styles = [
            {"label": label, "confidence": float(predicted_scores.get(label, 1.0) or 1.0)}
            for label in manual_styles
        ]
    if manual_flags:
        flags = {**flags, **manual_flags}
    entry["classification"] = {
        "presentation": {
            "label": manual_presentation or _value(prediction, "presentation_label"),
            "confidence": 1.0 if manual_presentation else _value(prediction, "presentation_confidence"),
        },
        "styles": styles,
        "flags": flags,
        "method": _value(prediction, "method"),
        "needsReview": bool(_value(prediction, "needs_review")),
    }
    return entry


def _value(row: Any, key: str) -> Any:
    if hasattr(row, "keys") and key in row.keys():
        return row[key]
    if isinstance(row, dict):
        return row.get(key)
    return None


def export_workspace(
    conn: Any,
    output: Path,
    fmt: str,
    approved_only: bool = True,
    include_classification: bool = True,
    style: str | None = None,
    presentation: str | None = None,
) -> int:
    where = ["o.rejected = 0"]
    params: list[Any] = []
    if approved_only:
        where.append("o.review_status IN ('approved', 'corrected')")
    if presentation:
        where.append("(l.presentation_label = ? OR p.presentation_label = ?)")
        params.extend([presentation, presentation])
    sql = """
        SELECT o.*, p.presentation_label, p.presentation_confidence, p.styles_json, p.flags_json,
               p.method, p.needs_review,
               l.presentation_label AS manual_presentation,
               l.style_labels_json AS manual_styles_json,
               l.flags_json AS manual_flags_json
        FROM outfits o
        LEFT JOIN predictions p ON p.entry_id = o.entry_id
        LEFT JOIN labels l ON l.entry_id = o.entry_id
        WHERE {where}
        ORDER BY o.group_id, o.rank, o.user_id, o.outfit_id
    """.format(where=" AND ".join(where))
    rows = list(conn.execute(sql, tuple(params)))
    entries = []
    for row in rows:
        entry = rows_to_entries([row])[0]
        if include_classification:
            entry = attach_classification(entry, row)
        if style:
            labels = {item.get("label") for item in entry.get("classification", {}).get("styles", [])}
            labels.update(json.loads(row["manual_styles_json"] or "[]"))
            if style not in labels:
                continue
        entries.append(entry)

    output.parent.mkdir(parents=True, exist_ok=True)
    if fmt == "json":
        collect_outfits.write_json(entries, output)
    else:
        write_lua_with_classification(entries, output)
    return len(entries)


def write_lua_with_classification(entries: list[dict[str, Any]], path: Path) -> None:
    lines = [
        "-- Generated by roblox_outfits workspace export",
        "return {",
    ]
    for entry in entries:
        fields = [
            f"source = {collect_outfits.lua_string(entry.get('source'))}",
            f"outfitId = {collect_outfits.lua_nil_or_number(entry.get('outfitId'))}",
            f"userId = {int(entry.get('userId'))}",
            f"groupId = {int(entry.get('groupId') or 0)}",
            f"rank = {int(entry.get('rank') or 0)}",
            f"currentMatch = {collect_outfits.lua_bool(entry.get('currentMatch'))}",
            f"avatarType = {collect_outfits.lua_string(entry.get('avatarType', 'unknown'))}",
            f"tags = {collect_outfits.lua_string_array(entry.get('tags', []))}",
            f"assetIds = {collect_outfits.lua_number_array(entry.get('assetIds', []))}",
            f"name = {collect_outfits.lua_string(entry.get('name', ''))}",
            f"username = {collect_outfits.lua_string(entry.get('username', ''))}",
            f"roleName = {collect_outfits.lua_string(entry.get('roleName', ''))}",
        ]
        classification = entry.get("classification")
        if classification:
            presentation = classification.get("presentation", {})
            styles = classification.get("styles", [])
            flags = classification.get("flags", {})
            active_flags = [key for key, value in flags.items() if value]
            fields.extend(
                [
                    f"presentation = {collect_outfits.lua_string(presentation.get('label') or '')}",
                    f"presentationConfidence = {_lua_float(presentation.get('confidence'))}",
                    f"styles = {collect_outfits.lua_string_array([item.get('label', '') for item in styles])}",
                    f"styleScores = {_lua_score_table(styles)}",
                    f"classificationFlags = {collect_outfits.lua_string_array(active_flags)}",
                    f"needsReview = {collect_outfits.lua_bool(classification.get('needsReview'))}",
                ]
            )
        lines.append("    { " + ", ".join(fields) + " },")
    lines.append("}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _lua_float(value: Any) -> str:
    if value is None:
        return "0"
    return f"{float(value):.4f}".rstrip("0").rstrip(".")


def _lua_score_table(styles: list[dict[str, Any]]) -> str:
    pairs = []
    for item in styles:
        label = str(item.get("label", ""))
        if label.isidentifier():
            pairs.append(f"{label} = {_lua_float(item.get('confidence'))}")
    return "{ " + ", ".join(pairs) + " }"
